export const en = {
  pageTitle: "Articles List",
  pageSubtitle: "Browse and manage all knowledge base articles",
  addArticle: "+ Add Article",
  filter: {
    searchTitle: "Search Title",
    searchPlaceholder: "Search article title…",
    category: "Category",
    categoryPlaceholder: "Select Category",
    createdDate: "Created Date",
    startCreatedDatePlaceholder: "Start Date",
    endCreatedDatePlaceholder: "End Date",
    createdBy: "Created By",
    createdByPlaceholder: "Select Author",
    status: "Status",
    statusPlaceholder: "Select Status",
    version: "Version",
    versionPlaceholder: "Version",
    group: "Group",
    groupPlaceholder: "Select Group",
    priority: "Priority",
    priorityPlaceholder: "Select Priority",
    score: "Score",
    scorePlaceholder: "Score",
    sortBy: "Sort By",
    sortByPlaceholder: "Sort By",
    resetFilter: "Reset",
  },
  status: {
    all: "All",
    publish: "Published",
    wait_approve: "Wait Approve",
    wait_publish: "Wait Publish",
    draft: "Draft",
    archived: "Archived",
    unpublished: "Un Published"
  },
  priority: {
    all: "All",
    high: "High",
    medium: "Medium",
    low: "Low",
  },
  user: {
    all: "All",
  },
  group: {
    all: "All",
  },
  sortBy: {
    title_az: "Title A–Z",
    title_za: "Title Z-A",
    createdDate_az: "Created Date A-Z",
    createdDate_za: "Created Date Z-A"
  },
  meta: {
    version: "Version",
    lastEdited: "Last Edited",
    views: "Views",
    priority: "Priority",
    category: "Category",
    viewCount: "views",
  },
  statusBadge: {
    publish: "Published",
    wait_approve: "Wait Approve",
    wait_publish: "Wait Publish",
    draft: "Draft",
    archived: "Archived",
    unpublished: "Un Published"
  },
  loading: "Loading articles…",
  noData: "No articles found",
  total: "total",
  pagination: {
    showing: "Showing",
    to: "to",
    of: "of",
    prev: "Previous",
    next: "Next",
    items: "items",
  },
  category: {
    pageTitle: "Category Manager",
    pageSubtitle:
      "Organize your knowledge base categories in a tree structure. Drag to reorder.",
    modalTitle: "Select Category",
    modalSubtitle: "Click a category to filter articles",
    backToArticles: "Back to Articles",
    all: "All Categories",
    searchPlaceholder: "Search categories…",
    sortBy: "Sort",
    addRoot: "Add Category",
    add: "Add",
    newCategory: "New Category",
    newCategoryPlaceholder: "Category name…",
    renamed: "Category renamed",
    deleted: "Category deleted",
    added: "Category added",
    errorGeneric: "Something went wrong",
    confirmDeleteTitle: "Delete Category?",
    confirmDeleteBody:
      "All child categories will also be removed. Articles in this category will become uncategorized.",
    delete: "Delete",
    cancel: "Cancel",
    dragHint: "Drag and drop to reorganize • Double-click to rename",
    noResults: "No categories match your search",
    empty: "No categories yet",
    selectButton: "Select Category",
    expandAll: "Expand all",
    collapseAll: "Collapse all",
  },
  form: {
    createTitle: "Create Article",
    editTitle: "Edit Article",
    eyebrow: "Knowledge Base",
    createSub: "Fill in the details to create a new article",
    editSub: "Edit the existing article information",
    saveBtn: "Save",
    saving: "Saving…",
    loading: "Loading data…",
    steps: {
      create: "Create",
      submit: "Submit",
      approve: "Approve",
      publish: "Publish",
    },
    tabs: {
      basic: "Basic Info",
      basicSub: "Basic Info",
      content: "Content",
      contentSub: "Content",
      visibility: "Visibility",
      visibilitySub: "Visibility & Settings",
    },
    basic: {
      titleLabel: "Title",
      titlePlaceholder: "Enter article title",
      versionLabel: "Version",
      descriptionLabel: "Article Description",
      descriptionPlaceholder: "Enter a short description",
      priorityLabel: "Priority",
      priorityPlaceholder: "Select Priority",
      sourceLabel: "Source",
      sourcePlaceholder: "Enter source",
      reserveDateLabel: "Reserve Date",
      ownershipLabel: "Ownership",
      ownershipPlaceholder: "Enter owner",
      relatedArticlesLabel: "Related Articles",
      relatedArticlesPlaceholder: "Type and press Enter…",
      groupArticlesPlaceholder: "Type and press Enter…",
      categoryLabel: "Category",
      categorySearch: "Search categories…",
      categoryEmpty: "No categories found",
      tagAdd: "Add",
      tagPlaceholder: "Type and press Enter…",
    },
    content: {
      attachmentLabel: "File Attachment",
      pickFromMinio: "Select files from MinIO",
      noFiles: "No files attached",
      contentLabel: "Content",
    },
    visibility: {
      startDateLabel: "Start Date",
      endDateLabel: "Expiration Date",
      viewableGroupsLabel: "Viewable Groups",
      viewableGroupsPlaceholder: "Type group name and press Enter…",
      keywordsLabel: "Keywords",
      keywordsPlaceholder: "Type keyword and press Enter…",
      tagAdd: "Add",
      tagPlaceholder: "Type and press Enter…",
    },
    nav: { prev: "Previous", next: "Next" },
    validation: { titleRequired: "Please enter a title" },
    success: "Article saved successfully!",
    errorGeneric: "Something went wrong",
    picker: {
      title: "Select Files from MinIO",
      subtitle: "Select files to attach to this article",
      confirm: "Confirm {{count}} file(s)",
      cancel: "Cancel",
      search: "Search files…",
      empty: "No files in this folder",
      noResults: "No files found",
      selectedCount: "{{count}} file(s) selected",
      noneSelected: "No files selected yet",
      allFiles: "All Files",
      folders: "Folders",
      files: "Files",
    },
  },
  detail: {
    eyebrow: "Article Detail",
    back: "Back to Articles",
    edit: "Edit Article",
    loading: "Loading article…",
    notFound: "Article not found",
    content: "Content",
    attachments: "Attachments",
    noAttachments: "No attachments",
    noContent: "No content available",
    metadata: "Information",
    category: "Category",
    group: "Group",
    author: "Author",
    ownership: "Ownership",
    source: "Source",
    views: "Views",
    rating: "Rating",
    score: "Score",
    version: "Version",
    startDate: "Start Date",
    endDate: "Expiration Date",
    createdAt: "Created",
    updatedAt: "Last Updated",
    viewableGroups: "Viewable Groups",
    keywords: "Keywords",
    relatedArticles: "Related Articles",
    noRelated: "No related articles",
    activityLog: "Activity Log",
    actions: {
      create: "Created",
      edit: "Edited",
      submit: "Submitted for Review",
      approve: "Approved",
      publish: "Published",
      archive: "Archived",
      draft: "Saved as Draft",
    },
  },
  review: {
    eyebrow: "Article Review",
    title: "Review Article",
    back: "Back",
    panel: "Review Decision",
    currentStatus: "Current Status",
    decisionLabel: "Decision",
    publish: "Published",
    wait_approve: "Wait Approve",
    wait_publish: "Wait Publish",
    draft: "Draft",
    archived: "Archived",
    unpublished: "Un Published",

    approve: "Approve",
    approveDesc: "Article is ready for publishing",
    changes: "Request Changes",
    changesDesc: "Ask author to revise before approval",
    reject: "Reject",
    rejectDesc: "Article does not meet requirements",
    note: "Notes / Comments",
    notePlaceholder: "Enter review notes or reasons…",
    submit: "Submit",
    submitting: "Submitting…",
    selectDecision: "Please select a decision",
    success: "Review submitted successfully",
    error: "Failed to submit review",
    coverImage: "Cover Image",
    noCover: "No cover image",
  },
  activityLog: {
    title: "Activity Log",
    viewAll: "View all activity",
    create: "Create Article",
    edit: "Edit Article",
    submit: "Submit Article",
    approve: "Approved Article",
    publish: "Publish Article",
    archive: "Archive Article",
    draft: "Draft Article",
  },
  coverImage: {
    change: "Change",
    delete: "Delete",
    copy: "Copy",
    download: "Download",
    edit: "Edit",
    deleteCoverImage: "Delete Cover Image",
    copyPath: "Copy Path",
    downloadImage: "Download Image",
    editImage: "Edit Image",
    deleteConfirmTitle: "Delete Cover Image?",
    deleteConfirmDescription:
      "Are you sure you want to delete the cover image? This action cannot be undone.",
    copyConfirmDescription: "Copy the image path to clipboard?",
    downloadConfirmDescription: "Download the cover image to your device?",
    cancel: "Cancel",
    confirm: "Confirm",
    processing: "Processing...",
    clickToEdit: "Click to edit",
    clickToAdd: "Click to add image",
    noCoverImage: "No cover image",
    copyError: "Unable to copy to clipboard",
    downloadError: "Unable to download image",
    actionFailed: "Action failed",
  },
  rating: {
    title: "Rating",
    yourRating: "Your Rating",
    outOf5: "out of 5",
    stars: "stars",
    submit: "Submit Rating",
    submitting: "Submitting...",
    success: "Rating submitted successfully",
    error: "Failed to submit rating",
  },
  comments: {
    title: "Comments",
    noComments: "No comments yet",
    writeComment: "Write a comment...",
    send: "Send",
    sending: "Sending...",
    reply: "Reply",
    replies: "replies",
    viewReplies: "View replies",
    hideReplies: "Hide replies",
    delete: "Delete",
    deleteConfirm: "Delete this comment?",
    cancel: "Cancel",
    success: "Comment added successfully",
    error: "Failed to add comment",
  },
  actions: {
    delete: "Delete",
    duplicate: "Copy",
    editContent: "New Version",
    certify: "Edit",
    deleteConfirmTitle: "Delete Article?",
    deleteConfirmDesc:
      "This action cannot be undone. The article will be permanently deleted.",
    cancel: "Cancel",
    confirmDelete: "Delete",
  },
} as const;

export const th = {
  pageTitle: "รายการบทความ",
  pageSubtitle: "ค้นหาและจัดการบทความทั้งหมดในฐานความรู้",
  addArticle: "+ เพิ่มบทความ",
  filter: {
    searchTitle: "ค้นหาหัวข้อ",
    searchPlaceholder: "ค้นหาหัวข้อบทความ…",
    category: "หมวดหมู่",
    categoryPlaceholder: "เลือกหมวดหมู่",
    createdDate: "วันที่สร้าง",
    startCreatedDatePlaceholder: "วันที่เริ่มต้น",
    endCreatedDatePlaceholder: "วันที่สิ้นสุด",
    createdBy: "ผู้สร้าง",
    createdByPlaceholder: "เลือกผู้สร้าง",
    status: "สถานะบทความ",
    statusPlaceholder: "เลือกสถานะ",
    version: "Version",
    versionPlaceholder: "Version",
    group: "Group",
    groupPlaceholder: "เลือก Group",
    priority: "ระดับความสำคัญ",
    priorityPlaceholder: "เลือกระดับ",
    score: "คะแนน",
    scorePlaceholder: "คะแนน",
    sortBy: "เรียงลำดับ",
    sortByPlaceholder: "เรียงลำดับ",
    resetFilter: "ล้างตัวกรอง",
  },
  status: {
    all: "ทั้งหมด",
    publish: "เผยแพร่แล้ว",
    wait_publish: "รอเผยแพร่",
    wait_approve: "รออนุมัติ",
    draft: "แบบร่าง",
    archived: "เก็บถาวร",
    unpublished: "ยกเลิกการเผยแพร่"
  },
  priority: {
    all: "ทั้งหมด",
    high: "สูง",
    medium: "กลาง",
    low: "ต่ำ",
  },
  user: {
    all: "ทั้งหมด",
  },
  group: {
    all: "ทั้งหมด",
  },
  sortBy: {
    title_az: "ชื่อ A–Z",
    title_za: "ชื่อ Z-A",
    createdDate_az: "วันที่สร้าง A-Z",
    createdDate_za: "วันที่สร้าง Z-A"
  },
  meta: {
    version: "เวอร์ชั่น",
    lastEdited: "แก้ไขล่าสุด",
    views: "การดู",
    priority: "ระดับ",
    category: "หมวดหมู่",
    viewCount: "รีวิว",
  },
  statusBadge: {
    publish: "เผยแพร่แล้ว",
    wait_publish: "รอเผยแพร่",
    wait_approve: "รออนุมัติ",
    draft: "แบบร่าง",
    archived: "เก็บถาวร",
    unpublished: "ยกเลิกการเผยแพร่"
  },
  loading: "กำลังโหลดบทความ…",
  noData: "ไม่พบบทความ",
  total: "รายการ",
  pagination: {
    showing: "แสดง",
    to: "ถึง",
    of: "จาก",
    prev: "ก่อนหน้า",
    next: "ถัดไป",
    items: "รายการ",
  },
  category: {
    pageTitle: "จัดการหมวดหมู่",
    pageSubtitle:
      "จัดระเบียบหมวดหมู่บทความในรูปแบบต้นไม้ ลากเพื่อเรียงลำดับใหม่",
    modalTitle: "เลือกหมวดหมู่",
    modalSubtitle: "คลิกหมวดหมู่เพื่อกรองบทความ",
    backToArticles: "กลับไปรายการบทความ",
    all: "ทุกหมวดหมู่",
    searchPlaceholder: "ค้นหาหมวดหมู่…",
    sortBy: "เรียง",
    addRoot: "เพิ่มหมวดหมู่",
    add: "เพิ่ม",
    newCategory: "หมวดหมู่ใหม่",
    newCategoryPlaceholder: "ชื่อหมวดหมู่…",
    renamed: "เปลี่ยนชื่อหมวดหมู่แล้ว",
    deleted: "ลบหมวดหมู่แล้ว",
    added: "เพิ่มหมวดหมู่แล้ว",
    errorGeneric: "เกิดข้อผิดพลาด",
    confirmDeleteTitle: "ลบหมวดหมู่?",
    confirmDeleteBody: "หมวดหมู่ย่อยทั้งหมดจะถูกลบด้วย",
    delete: "ลบ",
    cancel: "ยกเลิก",
    dragHint: "ลากวางเพื่อเรียงลำดับใหม่ • ดับเปิวเพื่อเปลี่ยนชื่อ",
    noResults: "ไม่พบหมวดหมู่",
    empty: "ยังไม่มีหมวดหมู่",
    selectButton: "เลือกหมวดหมู่",
    expandAll: "ขยายทั้งหมด",
    collapseAll: "หุบทั้งหมด",
  },
  form: {
    createTitle: "สร้างบทความ",
    editTitle: "แก้ไขบทความ",
    eyebrow: "Knowledge Base",
    createSub: "กรอกข้อมูลเพื่อสร้างบทความใหม่",
    editSub: "แก้ไขข้อมูลบทความที่มีอยู่",
    saveBtn: "บันทึก",
    saving: "กำลังบันทึก…",
    loading: "กำลังโหลดข้อมูล…",
    steps: {
      create: "สร้าง",
      submit: "ส่ง",
      approve: "อนุมัติ",
      publish: "เผยแพร่",
    },
    tabs: {
      basic: "ข้อมูลพื้นฐาน",
      basicSub: "Basic Info",
      content: "เนื้อหาบทความ",
      contentSub: "Content",
      visibility: "การมองเห็น",
      visibilitySub: "Visibility & Settings",
    },
    basic: {
      titleLabel: "ชื่อเรื่อง (Title)",
      titlePlaceholder: "ระบุชื่อบทความ",
      versionLabel: "เวอร์ชั่น (Version)",
      descriptionLabel: "คำอธิบายบทความ (Article Description)",
      descriptionPlaceholder: "ระบุคำอธิบายโดยย่อ",
      priorityLabel: "ลำดับความสำคัญ (Priority)",
      priorityPlaceholder: "เลือกลำดับความสำคัญ",
      sourceLabel: "แหล่งที่มา (Source)",
      sourcePlaceholder: "ระบุแหล่งที่มา",
      reserveDateLabel: "วันที่สำรอง (Reserve Date)",
      ownershipLabel: "ผู้รับผิดชอบ (Ownership)",
      ownershipPlaceholder: "ระบุผู้รับผิดชอบ",
      relatedArticlesLabel: "บทความที่เกี่ยวข้อง (Related Articles)",
      relatedArticlesPlaceholder: "พิมพ์ชื่อบทความแล้วกด Enter…",
      groupArticlesPlaceholder: "พิมพ์ชื่อกลุ่มแล้วกด Enter…",
      categoryLabel: "หมวดหมู่ (Category)",
      categorySearch: "ค้นหาหมวดหมู่…",
      categoryEmpty: "ไม่พบหมวดหมู่",
      tagAdd: "เพิ่ม",
      tagPlaceholder: "พิมพ์แล้วกด Enter…",
    },
    content: {
      attachmentLabel: "สิ่งแนบมาด้วย (File Attachment)",
      pickFromMinio: "เลือกไฟล์จาก MinIO",
      noFiles: "ยังไม่มีไฟล์แนบ",
      contentLabel: "เนื้อหาบทความ (Content)",
    },
    visibility: {
      startDateLabel: "วันที่เริ่มต้น (Start Date)",
      endDateLabel: "วันที่หมดอายุ (Expiration Date)",
      viewableGroupsLabel: "กลุ่มผู้มองเห็นได้ (Viewable Groups)",
      viewableGroupsPlaceholder: "พิมพ์ชื่อกลุ่มแล้วกด Enter…",
      keywordsLabel: "คำสำคัญ (Keywords)",
      keywordsPlaceholder: "พิมพ์คำสำคัญแล้วกด Enter…",
      tagAdd: "เพิ่ม",
      tagPlaceholder: "พิมพ์แล้วกด Enter…",
    },
    nav: { prev: "ก่อนหน้า", next: "ถัดไป" },
    validation: { titleRequired: "กรุณาระบุชื่อเรื่อง (Title)" },
    success: "บันทึกบทความสำเร็จ!",
    errorGeneric: "เกิดข้อผิดพลาด",
    picker: {
      title: "เลือกไฟล์จาก MinIO",
      subtitle: "เลือกไฟล์ที่ต้องการแนบกับบทความ",
      confirm: "ยืนยัน {{count}} ไฟล์",
      cancel: "ยกเลิก",
      search: "ค้นหาไฟล์…",
      empty: "ไม่มีไฟล์ในโฟลเดอร์นี้",
      noResults: "ไม่พบไฟล์",
      selectedCount: "เลือกแล้ว {{count}} ไฟล์",
      noneSelected: "ยังไม่ได้เลือกไฟล์",
      allFiles: "ไฟล์ทั้งหมด",
      folders: "โฟลเดอร์",
      files: "ไฟล์",
    },
  },
  review: {
    eyebrow: "พิจารณาบทความ",
    title: "พิจารณาบทความ",
    back: "กลับ",
    panel: "ผลการพิจารณา",
    currentStatus: "สถานะปัจจุบัน",
    decisionLabel: "ผลการพิจารณา",
    publish: "เผยแพร่แล้ว",
    wait_publish: "รอเผยแพร่",
    wait_approve: "รออนุมัติ",
    draft: "แบบร่าง",
    archived: "เก็บถาวร",
    unpublished: "ยกเลิกการเผยแพร่",
    approve: "อนุมัติ",
    approveDesc: "บทความพร้อมเผยแพร่",
    changes: "ขอแก้ไข",
    changesDesc: "ให้ผู้เขียนแก้ไขก่อนอนุมัติ",
    reject: "ปฏิเสธ",
    rejectDesc: "บทความไม่ผ่านเกณฑ์",
    note: "หมายเหตุ / ความเห็น",
    notePlaceholder: "ระบุเหตุผลหรือความเห็นสำหรับการพิจารณา…",
    // submit: "ยืนยันการพิจารณา",
    submit: "ยืนยันการ",
    submitting: "กำลังส่ง…",
    selectDecision: "กรุณาเลือกผลการพิจารณา",
    success: "ส่งผลการพิจารณาสำเร็จ",
    error: "เกิดข้อผิดพลาดในการส่งผล",
    coverImage: "รูปปก",
    noCover: "ไม่มีรูปปก",
  },
  activityLog: {
    title: "ประวัติการดำเนินการ",
    viewAll: "ดูประวัติทั้งหมด",
    create: "สร้างบทความ",
    edit: "แก้ไขบทความ",
    submit: "ส่งตรวจสอบ",
    approve: "อนุมัติแล้ว",
    publish: "เผยแพร่แล้ว",
    archive: "เก็บถาวร",
    draft: "บันทึกแบบร่าง",
  },
  detail: {
    eyebrow: "รายละเอียดบทความ",
    back: "กลับหน้าบทความ",
    edit: "แก้ไขบทความ",
    loading: "กำลังโหลดบทความ…",
    notFound: "ไม่พบบทความ",
    content: "เนื้อหา",
    attachments: "ไฟล์แนบ",
    noAttachments: "ไม่มีไฟล์แนบ",
    noContent: "ยังไม่มีเนื้อหา",
    metadata: "ข้อมูล",
    category: "หมวดหมู่",
    group: "กลุ่ม",
    author: "ผู้เขียน",
    ownership: "ผู้รับผิดชอบ",
    source: "แหล่งที่มา",
    views: "ยอดเข้าชม",
    rating: "คะแนน",
    score: "สกอร์",
    version: "เวอร์ชัน",
    startDate: "วันที่เริ่ม",
    endDate: "วันหมดอายุ",
    createdAt: "วันที่สร้าง",
    updatedAt: "แก้ไขล่าสุด",
    viewableGroups: "กลุ่มที่เข้าถึงได้",
    keywords: "คำสำคัญ",
    relatedArticles: "บทความที่เกี่ยวข้อง",
    noRelated: "ไม่มีบทความที่เกี่ยวข้อง",
    activityLog: "ประวัติการดำเนินการ",
    actions: {
      create: "สร้างบทความ",
      edit: "แก้ไขบทความ",
      submit: "ส่งตรวจสอบ",
      approve: "อนุมัติแล้ว",
      publish: "เผยแพร่แล้ว",
      archive: "เก็บถาวร",
      draft: "บันทึกแบบร่าง",
    },
  },
  coverImage: {
    change: "เปลี่ยน",
    delete: "ลบ",
    copy: "คัดลอก",
    download: "ดาวน์โหลด",
    edit: "แก้ไข",
    deleteCoverImage: "ลบรูปปก",
    copyPath: "คัดลอกเส้นทาง",
    downloadImage: "ดาวน์โหลดภาพ",
    editImage: "แก้ไขภาพ",
    deleteConfirmTitle: "ลบรูปปก?",
    deleteConfirmDescription:
      "คุณแน่ใจหรือว่าต้องการลบรูปปก การดำเนินการนี้ไม่สามารถเลิกทำได้",
    copyConfirmDescription: "คัดลอกเส้นทางรูปภาพไปยังคลิปบอร์ด?",
    downloadConfirmDescription: "ดาวน์โหลดรูปปกไปยังอุปกรณ์ของคุณ?",
    cancel: "ยกเลิก",
    confirm: "ยืนยัน",
    processing: "กำลังประมวลผล...",
    clickToEdit: "คลิกเพื่อแก้ไข",
    clickToAdd: "คลิกเพื่อเพิ่มรูปภาพ",
    noCoverImage: "ไม่มีรูปปก",
    copyError: "ไม่สามารถคัดลอกไปยังคลิปบอร์ด",
    downloadError: "ไม่สามารถดาวน์โหลดรูปภาพ",
    actionFailed: "การดำเนินการล้มเหลว",
  },
  rating: {
    title: "คะแนน",
    yourRating: "คะแนนของคุณ",
    outOf5: "จาก 5",
    stars: "ดาว",
    submit: "ส่งคะแนน",
    submitting: "กำลังส่ง...",
    success: "ส่งคะแนนสำเร็จ",
    error: "ไม่สามารถส่งคะแนน",
  },
  comments: {
    title: "ความเห็น",
    noComments: "ยังไม่มีความเห็น",
    writeComment: "เขียนความเห็น...",
    send: "ส่ง",
    sending: "กำลังส่ง...",
    reply: "ตอบกลับ",
    replies: "ตอบกลับ",
    viewReplies: "ดูการตอบกลับ",
    hideReplies: "ซ่อนการตอบกลับ",
    delete: "ลบ",
    deleteConfirm: "ลบความเห็นนี้?",
    cancel: "ยกเลิก",
    success: "เพิ่มความเห็นสำเร็จ",
    error: "ไม่สามารถเพิ่มความเห็น",
  },
  actions: {
    delete: "ลบ (Delete)",
    duplicate: "คัดลอก(Copy)",
    editContent: "สร้างเวอร์ชันใหม่",
    certify: "แก้ไข(Edits)",
    deleteConfirmTitle: "ลบบทความ?",
    deleteConfirmDesc:
      "การดำเนินการนี้ไม่สามารถเลิกทำได้ บทความจะถูกลบออกอย่างถาวร",
    cancel: "ยกเลิก",
    confirmDelete: "ลบ",
  },
} as const;
