export const en = {
  page: {
    title: "Files For Articles",
    metaTitle: "Files For Articles | TailAdmin",
    metaDescription:
      "Browse, upload, and manage files stored in MinIO for knowledge base articles.",
    subtitle:
      "Browse, upload, and manage files attached to knowledge base articles stored in object storage.",
    eyebrow: "File Manager",
  },
  sections: {
    recent: { title: "All Files", description: "Most recently accessed files across all folders" },
    folders: "Folders",
    files: "Files",
  },
  labels: {
    loading: "Loading files...",
    loadFailed: "Unable to load files.",
    empty: "No files found in this location.",
    noResults: "No files match your search.",
    files: "files",
    size: "size",
    apiPath: "API path",
    source: "Source",
    mock: "Mock",
    api: "API",
    lastOpen: "last open",
    fileCount: "{{count}} files, {{size}}",
    selectedCount: "{{count}} file(s) selected",
    noneSelected: "No files selected",
  },
  buttons: {
    upload: "Upload",
    uploading: "Uploading...",
    download: "Download",
    delete: "Delete",
    retry: "Retry",
    refresh: "Refresh",
    refreshing: "Refreshing...",
    newFolder: "New Folder",
    create: "Create",
    copyUrl: "Copy URL",
    cancel: "Cancel",
  },
  folder: { namePlaceholder: "Folder name…" },
  confirm: {
    delete: 'Delete "{{name}}"?',
    deleteFolder: 'Delete folder "{{name}}"?',
  },
  toast: {
    uploadSuccess: "File uploaded successfully.",
    uploadError: "Unable to upload file.",
    deleteSuccess: "File deleted.",
    deleteError: "Unable to delete file.",
    downloadError: "Unable to get download link.",
    folderCreated: "Folder created.",
    folderError: "Unable to create folder.",
    folderDeleteSuccess: "Folder deleted.",
    folderDeleteError: "Unable to delete folder.",
    copySuccess: "URL copied to clipboard.",
    copyError: "Unable to copy URL.",
  },
  tree: { title: "Folders" },
};

export const th = {
  page: {
    title: "ไฟล์ประกอบบทความ",
    metaTitle: "ไฟล์ประกอบบทความ | TailAdmin",
    metaDescription:
      "เรียกดู อัปโหลด และจัดการไฟล์ที่จัดเก็บใน MinIO สำหรับบทความใน Knowledge Base",
    subtitle:
      "เรียกดู อัปโหลด และจัดการไฟล์ที่แนบกับบทความ Knowledge Base ซึ่งจัดเก็บใน Object Storage",
    eyebrow: "จัดการไฟล์",
  },
  sections: {
    recent: { title: "ไฟล์ทั้งหมด", description: "ไฟล์ที่เข้าถึงล่าสุดจากทุกโฟลเดอร์" },
    folders: "โฟลเดอร์",
    files: "ไฟล์",
  },
  labels: {
    loading: "กำลังโหลดไฟล์...",
    loadFailed: "ไม่สามารถโหลดไฟล์ได้",
    empty: "ไม่พบไฟล์ในตำแหน่งนี้",
    noResults: "ไม่พบไฟล์ที่ตรงกับการค้นหา",
    files: "ไฟล์",
    size: "ขนาด",
    apiPath: "เส้นทาง API",
    source: "แหล่งข้อมูล",
    mock: "ข้อมูลจำลอง",
    api: "API",
    lastOpen: "เปิดล่าสุด",
    fileCount: "{{count}} ไฟล์, {{size}}",
    selectedCount: "เลือกแล้ว {{count}} ไฟล์",
    noneSelected: "ยังไม่ได้เลือกไฟล์",
  },
  buttons: {
    upload: "อัปโหลด",
    uploading: "กำลังอัปโหลด...",
    download: "ดาวน์โหลด",
    delete: "ลบ",
    retry: "ลองอีกครั้ง",
    refresh: "รีเฟรช",
    refreshing: "กำลังรีเฟรช...",
    newFolder: "โฟลเดอร์ใหม่",
    create: "สร้าง",
    copyUrl: "คัดลอก URL",
    cancel: "ยกเลิก",
  },
  folder: { namePlaceholder: "ชื่อโฟลเดอร์…" },
  confirm: {
    delete: 'ลบ "{{name}}" ใช่หรือไม่?',
    deleteFolder: 'ลบโฟลเดอร์ "{{name}}" ใช่หรือไม่?',
  },
  toast: {
    uploadSuccess: "อัปโหลดไฟล์สำเร็จ",
    uploadError: "ไม่สามารถอัปโหลดไฟล์ได้",
    deleteSuccess: "ลบไฟล์สำเร็จ",
    deleteError: "ไม่สามารถลบไฟล์ได้",
    downloadError: "ไม่สามารถสร้างลิงก์ดาวน์โหลดได้",
    folderCreated: "สร้างโฟลเดอร์สำเร็จ",
    folderError: "ไม่สามารถสร้างโฟลเดอร์ได้",
    folderDeleteSuccess: "ลบโฟลเดอร์สำเร็จ",
    folderDeleteError: "ไม่สามารถลบโฟลเดอร์ได้",
    copySuccess: "คัดลอก URL แล้ว",
    copyError: "ไม่สามารถคัดลอก URL ได้",
  },
  tree: { title: "โฟลเดอร์" },
};
