export const en = {
  page: {
    title: "Source Manager",
    metaTitle: "Source Manager | TailAdmin",
    metaDescription:
      "Manage article source master data — add, edit, and remove source entries.",
    subtitle:
      "Manage the list of article sources used across the knowledge base. Add, edit, or remove source entries from this workspace.",
  },
  sections: {
    list: {
      title: "Source List",
      description: "All source entries in the system",
    },
  },
  labels: {
    loading: "Loading source data...",
    loadFailed: "Unable to load source data.",
    empty: "No source entries found.",
    apiPath: "API path",
    source: "Source",
    mock: "Mock",
    api: "API",
    active: "Active",
    inactive: "Inactive",
    nameTh: "Name (TH)",
    nameEn: "Name (EN)",
    seq: "Order",
    status: "Status",
    actions: "Actions",
    no: "#",
  },
  buttons: {
    add: "Add Source",
    edit: "Edit",
    delete: "Delete",
    deleteConfirm: "Delete source",
    cancel: "Cancel",
    create: "Create Source",
    update: "Save Changes",
    saving: "Saving...",
    refresh: "Refresh",
    refreshing: "Refreshing...",
  },
  form: {
    createTitle: "Add Source",
    editTitle: "Edit Source",
    description: "Fill in the source name in Thai and English, and set display order.",
    nameTh: "Name (Thai)",
    nameEn: "Name (English)",
    seq: "Display order",
    isActive: "Active",
    validationNameTh: "Please enter a Thai name",
    validationNameEn: "Please enter an English name",
    validationSeq: "Display order must be a positive number",
  },
  pagination: {
    showing: "Showing {{from}}–{{to}} of {{total}}",
    prev: "Previous",
    next: "Next",
  },
  confirm: {
    delete: 'Delete "{{name}}"?',
    deleteDescription: "This action cannot be undone.",
  },
  toast: {
    createSuccess: "Source created successfully.",
    createError: "Unable to create the source.",
    updateSuccess: "Source updated successfully.",
    updateError: "Unable to update the source.",
    deleteSuccess: "Source deleted successfully.",
    deleteError: "Unable to delete the source.",
  },
};

export const th = {
  page: {
    title: "จัดการแหล่งที่มา",
    metaTitle: "จัดการแหล่งที่มา | TailAdmin",
    metaDescription:
      "จัดการข้อมูลหลักแหล่งที่มาของบทความ — เพิ่ม แก้ไข และลบรายการ",
    subtitle:
      "จัดการรายการแหล่งที่มาของบทความที่ใช้งานในระบบ สามารถเพิ่ม แก้ไข หรือลบรายการได้จากหน้านี้",
  },
  sections: {
    list: {
      title: "รายการแหล่งที่มา",
      description: "รายการแหล่งที่มาทั้งหมดในระบบ",
    },
  },
  labels: {
    loading: "กำลังโหลดข้อมูลแหล่งที่มา...",
    loadFailed: "ไม่สามารถโหลดข้อมูลแหล่งที่มาได้",
    empty: "ไม่พบรายการแหล่งที่มา",
    apiPath: "เส้นทาง API",
    source: "แหล่งข้อมูล",
    mock: "ข้อมูลจำลอง",
    api: "API",
    active: "ใช้งาน",
    inactive: "ปิดใช้งาน",
    nameTh: "ชื่อ (ไทย)",
    nameEn: "ชื่อ (อังกฤษ)",
    seq: "ลำดับ",
    status: "สถานะ",
    actions: "การดำเนินการ",
    no: "#",
  },
  buttons: {
    add: "เพิ่มแหล่งที่มา",
    edit: "แก้ไข",
    delete: "ลบ",
    deleteConfirm: "ลบแหล่งที่มา",
    cancel: "ยกเลิก",
    create: "สร้างแหล่งที่มา",
    update: "บันทึกการแก้ไข",
    saving: "กำลังบันทึก...",
    refresh: "รีเฟรช",
    refreshing: "กำลังรีเฟรช...",
  },
  form: {
    createTitle: "เพิ่มแหล่งที่มา",
    editTitle: "แก้ไขแหล่งที่มา",
    description: "กรอกชื่อแหล่งที่มาภาษาไทยและอังกฤษ พร้อมกำหนดลำดับการแสดงผล",
    nameTh: "ชื่อ (ภาษาไทย)",
    nameEn: "ชื่อ (ภาษาอังกฤษ)",
    seq: "ลำดับการแสดงผล",
    isActive: "เปิดใช้งาน",
    validationNameTh: "กรุณากรอกชื่อภาษาไทย",
    validationNameEn: "กรุณากรอกชื่อภาษาอังกฤษ",
    validationSeq: "ลำดับการแสดงผลต้องเป็นตัวเลขที่มากกว่า 0",
  },
  pagination: {
    showing: "แสดง {{from}}–{{to}} จาก {{total}} รายการ",
    prev: "ก่อนหน้า",
    next: "ถัดไป",
  },
  confirm: {
    delete: 'ลบ "{{name}}" ใช่หรือไม่?',
    deleteDescription: "การดำเนินการนี้ไม่สามารถยกเลิกได้",
  },
  toast: {
    createSuccess: "เพิ่มแหล่งที่มาสำเร็จ",
    createError: "ไม่สามารถเพิ่มแหล่งที่มาได้",
    updateSuccess: "บันทึกการแก้ไขแหล่งที่มาสำเร็จ",
    updateError: "ไม่สามารถแก้ไขแหล่งที่มาได้",
    deleteSuccess: "ลบแหล่งที่มาสำเร็จ",
    deleteError: "ไม่สามารถลบแหล่งที่มาได้",
  },
};
