// /src/pages/Workflow/Editor.tsx
/**
 * @fileoverview Code generated by Claude Sonnet 4 model.
 * 
 * @description
 * The workflow visual editor specifically for Case Management System use.
 * This will include case-specific node types, priority levels, case categories, SLA management, and case lifecycle features.
 * 
 * @metadata
 * Author: [Wisarud Techa]
 * First Created: [14-11-2025] v0.3.0
 * Last Updated: [14-11-2025] v0.3.0
 * 
 * @notes
 * - Auto-generated code; may contain incomplete logic or require validation.
 * - Modify with caution and document changes.
 * - Intended as a starting point or scaffolding.
 */

import React from "react";
import { useParams } from "react-router-dom";
import { ProtectedRoute } from "@/core/components/auth/ProtectedRoute";
import { FormManager } from "@/cms/components/interface/FormField";
import { useTranslation } from "@/core/hooks/useTranslation";
import { useGetAllFormsQuery } from "@/cms/store/api/formApi";
import { useReadOrderStatusQuery } from "@/cms/store/api/inventoryRequestApi";
import { useGetCaseStatusesQuery } from "@/cms/store/api/serviceApi";
import { useGetUsersQuery, useGetUserGroupQuery } from "@/core/store/api/userApi";
import { useGetWorkflowQuery } from "@/cms/store/api/workflowApi";
import type { CaseStatus } from "@/cms/types/case";
import type { RequestStatus } from "@/cms/types/inventoryRequest";
import type { UserProfile, UserGroup } from "@/core/types/user";
import type { WorkflowData } from "@/cms/types/workflow";
import PageBreadcrumb from "@/core/components/common/PageBreadCrumb";
import PageMeta from "@/core/components/common/PageMeta";
import WorkflowEditorComponent from "@/cms/components/workflow/editor/Editor";

const WorkflowEditorPage: React.FC = () => {
  const params = useParams<{ id: string, action: string }>();
  const { language, t } = useTranslation();

  const id = params?.id;
  const action = params?.action;

  const workflowId = id || "new";
  const workflowAction = id && action || "";
  const workflowHeader = language === "th" && (workflowId !== "new" && "แก้ไข" || "สร้าง") || (workflowId !== "new" && "Edit" || "Create");

  const threeLayerBreadcrumb = [
    { label: t("navigation.home"), href: "/" },
    { label: t("navigation.sidebar.main.workflow.nested.workflow_management"), href: "/workflow/list" },
    { label: t("navigation.sidebar.main.workflow.nested.workflow_builder.header").replace("_MODE_", workflowHeader) },
  ];

  // ===================================================================
  // API Data
  // ===================================================================
  const { data: caseStatusesData } = useGetCaseStatusesQuery({ start: 0, length: 30 });
  const caseStatuses = caseStatusesData?.data as unknown as CaseStatus[] || [];

  const { data: formsData } = useGetAllFormsQuery({ start: 0, length: 100, search: "" });
  const forms = formsData?.data as unknown as FormManager[] || [];

  const { data: usersData } = useGetUsersQuery({ start: 0, length: 1000 });
  const users = usersData?.data as unknown as UserProfile[] || [];

  const { data: userGroupData } = useGetUserGroupQuery({ start: 0, length: 100 });
  const userGroup = userGroupData?.data as unknown as UserGroup[] || [];

  const { data: workflowData } = useGetWorkflowQuery(id || "", { skip: !id });
  const workflow = workflowData?.data as unknown as WorkflowData || {};

  const { data: requestStatusesData } = useReadOrderStatusQuery({ start: 0, length: 30 });
  const requestStatuses = requestStatusesData?.data as unknown as RequestStatus[] || [];

  return (
    <>
      <PageMeta
        title="React.js Workflow Visual Editor | TailAdmin - Next.js Admin Dashboard Template"
        description="This is React.js Workflow Visual Editor for TailAdmin - React.js Tailwind CSS Admin Dashboard Template"
      />

      <ProtectedRoute requiredPermissions={["workflow.view"]}>
        <PageBreadcrumb items={threeLayerBreadcrumb} />

        <WorkflowEditorComponent
          workflowId={workflowId}
          workflowAction={workflowAction}
          workflowData={workflow}
          forms={forms}
          users={users}
          userGroup={userGroup}
          caseStatuses={caseStatuses}
          requestStatuses={requestStatuses}
        />
      </ProtectedRoute>
    </>
  );
};

export default WorkflowEditorPage;

/**
 * @keyFeatures
 * ----------------------------------------------------------------------------
 * Case Management Enhancements
 * - Total SLA Counting.
 * - Nodes must have at least Start, Dispatch, and End.
 * - Processes must have at least New Case and Close action.
 * 
 * @version 0.3.0
 * @date    14-11-2025
 * ----------------------------------------------------------------------------
 */
