// /src/pages/Workflow/List.tsx
/**
 * @fileoverview Code generated by Claude Sonnet 4 model.
 * 
 * @description
 * React TypeScript component for listing workflows with navigation functionality.
 * This will include fetching data from an API,
 * displaying workflows in a clean list format, and handling click navigation.
 * 
 * @metadata
 * Author: [Wisarud Techa]
 * First Created: [11-06-2025] v0.1.0
 * Last Updated: [11-07-2025] v0.1.4
 * 
 * @notes
 * - Auto-generated code; may contain incomplete logic or require validation.
 * - Modify with caution and document changes.
 * - Intended as a starting point or scaffolding.
 */

import React from "react";
import { ProtectedRoute } from "@/core/components/auth/ProtectedRoute";
import { useTranslation } from "@/core/hooks/useTranslation";
import { useGetWorkflowsQuery } from "@/cms/store/api/workflowApi";
import type { Workflow, WorkflowPagination } from "@/cms/types/workflow";
import PageBreadcrumb from "@/core/components/common/PageBreadCrumb";
import PageMeta from "@/core/components/common/PageMeta";
import WorkflowListComponent from "@/cms/components/workflow/list/List";

const WorkflowListPage: React.FC = () => {
  const { t } = useTranslation();

  // ===================================================================
  // API Data
  // ===================================================================
  const { data: workflowsData } = useGetWorkflowsQuery({ wfType: "case" }, { skip: false });
  const workflows = workflowsData?.data as unknown as Workflow[] || [];
  const workflowsPagination: WorkflowPagination = {
    currentPage: workflowsData?.currentPage || 1,
    pageSize: workflowsData?.pageSize || 1,
    totalFiltered: workflowsData?.totalFiltered || 0,
    totalPage: workflowsData?.totalPage || 1,
    totalRecords: workflowsData?.totalRecords || 0,
  };

  return workflows ? (
    <>
      <PageMeta
        title="React.js Workflow Management | TailAdmin - Next.js Admin Dashboard Template"
        description="This is React.js Workflow Management page for TailAdmin - React.js Tailwind CSS Admin Dashboard Template"
      />

      <ProtectedRoute requiredPermissions={["workflow.view"]}>
        <PageBreadcrumb pageTitle={t("navigation.sidebar.main.workflow.nested.workflow_management")} />

        <WorkflowListComponent workflows={workflows} workflowsPagination={workflowsPagination} />
      </ProtectedRoute>
    </>
  ) : (
    <div>Loading...</div>
  );
};

export default WorkflowListPage;

/**
 * @keyFeatures
 * ----------------------------------------------------------------------------
 * - Fetches workflows from API using useEffect and useState hooks.
 * - Displays workflows in a clean, clickable list format.
 * - Uses functional components with TypeScript interfaces.
 * - Each item is clickable for navigation (currently shows alert, ready for router).
 * 
 * @version 0.1.0
 * @date    11-06-2025
 * ----------------------------------------------------------------------------
 * - Display Mode Options.
 * - Complete CRUD Operations.
 * - Search Functionality.
 * - Filtering & Sorting.
 * - Pagination System.
 * - Show Entries Options.
 * - Status Management.
 * - Action Buttons.
 * - Confirmation Dialogs.
 * - Toast Notifications.
 * 
 * @version 0.1.1
 * @date    13-06-2025
 * ----------------------------------------------------------------------------
 * CRUD Components Extraction
 * - New CRUD pages need minimal code.
 * - Same patterns across all entities.
 * - Full TypeScript support with generics.
 * - Isolated, focused components.
 * - Changes in one place affect all CRUD operations.
 * - Easy to add new features to all entities.
 * 
 * @version 0.1.2
 * @date    09-07-2025
 * ----------------------------------------------------------------------------
 * Real Functional Operations
 * - Actual Delete Operations.
 * - Toast Notifications.
 * - Bulk Operations and Selection.
 * - Export Functionality.
 * - Real-time Updates.
 * - Advanced Filtering.
 * - Smart Pagination.
 * - Optimistic Updates.
 * 
 * @version 0.1.3
 * @date    10-07-2025
 * ----------------------------------------------------------------------------
 * Interactive Preview Dialog System
 * - Item Click Detection.
 * - Smart Event Handling.
 * - Visual Feedback.
 * - Tabbed Interface.
 * - Field Type System.
 * - Navigation Controls.
 * - Copyable Fields.
 * - Keyboard Shortcuts.
 * 
 * @version 0.1.4
 * @date    11-07-2025
 * ----------------------------------------------------------------------------
 */
